# Generated by Django 3.2.9 on 2021-12-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='value',
        ),
    ]
