# Generated by Django 3.2.9 on 2021-12-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_alter_like_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'image'), name='unique_like'),
        ),
    ]
